# https://www.mkdocs.org/user-guide/configuration/

site_name: Viet's Personal Setup
site_description: Setup & configuration steps to setup a computers
site_author: thanhoangviet@gmail.com
copyright: 
repo_url: https://github.com/VietThan/PersonalSetup


nav:
  - 'Starting Point' : 'index.md'
  - 'General Setup': 
    - 'Shell Setup' : 'general/shell-setup.md'
    - 'VSCode Setup' : 'general/vscode-setup.md'
  - 'Operating Systems':
    - 'Mac Setup':
      - 'os/mac/index.md'
    - 'Linux Setup':
      - 'os/linux/index.md'
    - 'Windows Setup':
      - 'os/windows/index.md'
  - 'Languages':
    - 'languages/index.md'
    - 'Python Setup': 'languages/python-setup.md'
  - 'Tools':
    - 'tools/index.md'
    - 'AWS Setup' : 'tools/aws-setup.md'
    - 'Wireshark Setup' : 'tools/wireshark-setup.md'
  - 'Browsers':
    - 'Chrome Setup' : 'browsers/chrome-setup.md'
    - 'Firefox Setup' : 'browsers/firefox-setup.md'
    - 'Safari Setup' : 'browsers/safari-setup.md'

markdown_extensions:
  - admonition # very useful to make tooltips or collapsibles : https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji: # add more emojis with https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


theme:
  name: "material"

plugins:
- search
- section-index
