# https://www.mkdocs.org/user-guide/configuration/

site_name: Viet's Personal Setup
site_description: Setup & configuration steps to setup a computers
site_author: thanhoangviet@gmail.com
copyright: 
repo_url: https://github.com/VietThan/PersonalSetup


nav:
  - 'Home': 
    - 'index.md'
    - 'Shell Setup' : 'shell-setup.md'
    - 'VSCode Setup' : 'vscode-setup.md'
  - 'Mac':
    - 'mac/index.md'
  # - 'Development' :
  #   - 'Getting Started' : 'development/getting-started.md'
  #   - 'VSCode Setup' : 'development/vscode-setup.md'
  #   - 'Pycharm Setup' : 'development/pycharm-setup.md'
  #   - 'Pre-Commit Setup' : 'development/pre-commit-setup.md'
  #   - 'Testing' : 'development/testing.md'
  #   - 'Managing Dependencies' : 'development/managing-dependencies.md'
  # - 'Projects' :
  #     - 'Promify API' :
  #       - 'Overview' : 'projects/promify-api/index.md'
  #       - 'Setup' : 'projects/promify-api/promify-api-setup.md'
  #       - 'Services' :
  #         - 'Promify API' : 'projects/promify-api/services/promify-api-service.md'
  #         - 'Websockify Bridge' : 'projects/promify-api/services/websockify-bridge.md'
  #       - 'History' : 'projects/promify-api/history.md'
  # - 'Monitoring & Logging' : 'monitoring-and-logging.md'
  # - 'Code References' : references/

markdown_extensions:
  - admonition # very useful to make tooltips or collapsibles : https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji: # add more emojis with https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


theme:
  name: "material"

plugins:
- search
- section-index
